In [5]:
import pandas as pd
import seaborn as sns
import numpy as np

In [90]:
def load_and_process(path_to_csv_file):
    data = (pd.read_csv(path_to_csv_file)
    .drop(columns =['CF','CA','SCF','SCA','TOI', 'Unnamed: 2'])
    )
    return data

In [91]:
df = load_and_process("../data/raw/Games - Natural Stat TrickTeam Season Totals - Natural Stat Trick.csv")
df

,Game,Team,CF%,SCF%,SH%,SV%,PDO
0,"2021-01-13 - Blackhawks 1, Lightning 5",Chicago Blackhawks,49.25,44.19,0.00,86.36,0.864
1,"2021-01-13 - Blackhawks 1, Lightning 5",Tampa Bay Lightning,50.75,55.81,13.64,100.00,1.136
2,"2021-01-13 - Blues 4, Avalanche 1",Colorado Avalanche,50.57,33.33,0.00,85.19,0.852
3,"2021-01-13 - Blues 4, Avalanche 1",St Louis Blues,49.43,66.67,14.81,100.00,1.148
4,"2021-01-13 - Canadiens 4, Maple Leafs 5",Montreal Canadiens,47.47,45.45,9.09,90.00,0.991
...,...,...,...,...,...,...,...
1731,"2021-05-16 - Flames 6, Canucks 5",Vancouver Canucks,39.02,47.22,8.70,78.26,0.870
1732,"2021-05-18 - Flames 2, Canucks 4",Calgary Flames,53.75,59.52,3.33,86.36,0.897
1733,"2021-05-18 - Flames 2, Canucks 4",Vancouver Canucks,46.25,40.48,13.64,96.67,1.103
1734,"2021-05-19 - Canucks 2, Flames 6",Calgary Flames,55.13,62.50,24.00,94.44,1.184
1735,"2021-05-19 - Canucks 2, Flames 6",Vancouver Canucks,44.87,37.50,5.56,76.00,0.816

In [92]:
def Canucks_Before_Data(data):
    data1= (data.drop(data[data.Team.isin(["Arizona Coyotes", "Buffalo Sabres", "Boston Bruins", "Carolina Hurricanes", "Columbus Blue Jackets", "Calgary Flames", "Chicago Blackhawks", "Colorado Avalanche", "Dallas Stars", "Detroit Red Wings", "Florida Panthers", "Los Angeles Kings", "Minnesota Wild", "Nashville Predators", "Pittsburgh Penguins", "San Jose Sharks", "Tampa Bay Lightning", "St Louis Blues", "Vegas Golden Knights", "Edmonton Oilers", "Montreal Canadiens", "New Jersey Devils", "New York Islanders", "New York Rangers", "Ottawa Senators", "Philadelphia Flyers", "Toronto Maple Leafs", "Winnipeg Jets", "Washington Capitals", "Anaheim Ducks"])].index)
    .reset_index()
    .drop(data.index[0:27]).drop(data.index[47:56])
    .reset_index().drop(columns = "index")
    .drop(columns =['level_0'])
    .drop(data.index[10:20])
           )
    return data1

In [93]:
Canucks_Before = Canucks_Before_Data(df)

In [94]:
def Canucks_After_Data(data):
    data2= (data.drop(data[data.Team.isin(["Arizona Coyotes", "Buffalo Sabres", "Boston Bruins", "Carolina Hurricanes", "Columbus Blue Jackets", "Calgary Flames", "Chicago Blackhawks", "Colorado Avalanche", "Dallas Stars", "Detroit Red Wings", "Florida Panthers", "Los Angeles Kings", "Minnesota Wild", "Nashville Predators", "Pittsburgh Penguins", "San Jose Sharks", "Tampa Bay Lightning", "St Louis Blues", "Vegas Golden Knights", "Edmonton Oilers", "Montreal Canadiens", "New Jersey Devils", "New York Islanders", "New York Rangers", "Ottawa Senators", "Philadelphia Flyers", "Toronto Maple Leafs", "Winnipeg Jets", "Washington Capitals", "Anaheim Ducks"])].index)
    .reset_index()
    .drop(data.index[0:27]).drop(data.index[47:56])
    .reset_index().drop(columns = "index")
    .drop(columns =['level_0'])
    .drop(data.index[0:10]).drop(data.index[20:20])
           )
    return data2

In [95]:
Canucks_After = Canucks_After_Data(df)

In [96]:
def Sabres_Before_Data(data):
    data3 = (data.drop(data[data.Team.isin(["Arizona Coyotes", "Vancouver Canucks", "Boston Bruins", "Carolina Hurricanes", "Columbus Blue Jackets", "Calgary Flames", "Chicago Blackhawks", "Colorado Avalanche", "Dallas Stars", "Detroit Red Wings", "Florida Panthers", "Los Angeles Kings", "Minnesota Wild", "Nashville Predators", "Pittsburgh Penguins", "San Jose Sharks", "Tampa Bay Lightning", "St Louis Blues", "Vegas Golden Knights", "Edmonton Oilers", "Montreal Canadiens", "New Jersey Devils", "New York Islanders", "New York Rangers", "Ottawa Senators", "Philadelphia Flyers", "Toronto Maple Leafs", "Winnipeg Jets", "Washington Capitals", "Anaheim Ducks"])].index)
    .reset_index()
    .drop(data.index[20:56])
    .drop(data.index[10:20])
    .drop(columns = "index")
    )
    
    return data3

In [97]:
Sabres_Before = Sabres_Before_Data(df)

In [98]:
def Sabres_After_Data(data):
    data4 = (data.drop(data[data.Team.isin(["Arizona Coyotes", "Vancouver Canucks", "Boston Bruins", "Carolina Hurricanes", "Columbus Blue Jackets", "Calgary Flames", "Chicago Blackhawks", "Colorado Avalanche", "Dallas Stars", "Detroit Red Wings", "Florida Panthers", "Los Angeles Kings", "Minnesota Wild", "Nashville Predators", "Pittsburgh Penguins", "San Jose Sharks", "Tampa Bay Lightning", "St Louis Blues", "Vegas Golden Knights", "Edmonton Oilers", "Montreal Canadiens", "New Jersey Devils", "New York Islanders", "New York Rangers", "Ottawa Senators", "Philadelphia Flyers", "Toronto Maple Leafs", "Winnipeg Jets", "Washington Capitals", "Anaheim Ducks"])].index)
.reset_index()
.drop(data.index[0:10])
.drop(data.index[20:56])
.drop(columns = "index")
            )
    return data4

In [99]:
Sabres_After = Sabres_After_Data(df)

In [100]:
def Describe(data):
    return data.describe().T

In [101]:
Describe(Sabres_Before)

      count     mean       std     min       25%     50%       75%     max
CF%    10.0  50.6840  5.281671  41.670  49.08000  51.110  53.25500  59.380
SCF%   10.0  51.6020  9.615050  36.360  45.07500  54.860  57.49500  63.330
SH%    10.0   6.7640  4.886915   0.000   4.40000   5.835  10.39750  13.640
SV%    10.0  90.7250  4.427581  80.950  88.80000  90.890  93.97250  96.150
PDO    10.0   0.9749  0.053733   0.915   0.93125   0.965   1.01025   1.081